In [4]:
import numpy as np

## DataTypes & Attributes

In [5]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
 a2 = np.array([[1, 2.0, 3.3],
                [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
               [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim # number of dimension

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
a1.size, a2.size, a3.size # how many elements we got totals in our arrays

(3, 6, 18)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [19]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [21]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [22]:
sample_array.dtype

dtype('int64')

In [24]:
ones = np.ones((2, 3))

In [25]:
ones.dtype

dtype('float64')

In [26]:
type(ones)

numpy.ndarray

In [29]:
zeroes = np.zeros((2, 3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [35]:
random_array = np.random.randint(0, 10,size=(3, 5))
random_array

array([[3, 0, 6, 3, 9],
       [4, 5, 0, 8, 8],
       [3, 9, 3, 7, 6]])

In [36]:
random_array.size

15

In [38]:
random_array.shape

(3, 5)

In [40]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.68197986, 0.80780424, 0.86501665],
       [0.02458487, 0.47104045, 0.65983182],
       [0.23368594, 0.72203581, 0.56342013],
       [0.7703826 , 0.11840221, 0.43820209],
       [0.42677496, 0.87622431, 0.91457065]])

In [42]:
random_array_2.shape

(5, 3)

In [43]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.14330853, 0.34124424, 0.80384098],
       [0.64424773, 0.82952251, 0.05555714],
       [0.73045733, 0.47404833, 0.57759925],
       [0.37746526, 0.55308014, 0.5283908 ],
       [0.14937021, 0.7046376 , 0.06673985]])

In [97]:
# Pseudo-random numbers
np.random.seed(seed=5555)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[2, 3, 0],
       [5, 2, 0],
       [3, 8, 8],
       [0, 7, 1],
       [5, 3, 0]])

In [129]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [131]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.20484909, 0.49076589, 0.37238469],
       [0.47740115, 0.36589039, 0.83791799],
       [0.76864751, 0.31399468, 0.57262533],
       [0.27604905, 0.45284293, 0.35297837],
       [0.65739946, 0.37035108, 0.45909298]])

In [98]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matices