In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
 a2 = np.array([[1, 2.0, 3.3],
                [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
               [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim # number of dimension

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
a1.size, a2.size, a3.size # how many elements we got totals in our arrays

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [17]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [19]:
ones = np.ones((2, 3))

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeroes = np.zeros((2, 3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10,size=(3, 5))
random_array

array([[7, 3, 0, 5, 7],
       [1, 6, 8, 0, 7],
       [2, 2, 2, 7, 5]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.89743629, 0.93995169, 0.62434364],
       [0.52419747, 0.30980666, 0.74333591],
       [0.67571542, 0.54433014, 0.61036558],
       [0.91374442, 0.1741281 , 0.48259475],
       [0.03329345, 0.11502783, 0.49570473]])

In [28]:
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.24067441, 0.03222908, 0.51457883],
       [0.14390799, 0.36637574, 0.69145779],
       [0.31212104, 0.85590146, 0.89736002],
       [0.58334661, 0.7270325 , 0.47863158],
       [0.29042267, 0.00589062, 0.01049371]])

In [30]:
# Pseudo-random numbers
np.random.seed(seed=5555)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[2, 3, 0],
       [5, 2, 0],
       [3, 8, 8],
       [0, 7, 1],
       [5, 3, 0]])

In [31]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [32]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [33]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matices

In [34]:
np.unique(random_array_4)

array([0, 1, 2, 3, 5, 7, 8])

In [35]:
a1

array([1, 2, 3])

In [36]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [37]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
a1[0]

1

In [39]:
a2.shape

(2, 3)

In [40]:
a2[0]

array([1. , 2. , 3.3])

In [41]:
a3.shape

(2, 3, 3)

In [42]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [45]:
a2[1]

array([4. , 5. , 6.5])

In [46]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [48]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [49]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [50]:
# Get the first 4 numbers of the inner most array
a4[:, :, :, :4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

## 4.Manipulating & comparing arrays

### Arithmetic

In [52]:
a1

array([1, 2, 3])

In [53]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [54]:
a1 + ones

array([2., 3., 4.])

In [57]:
a1 - ones

array([0., 1., 2.])

In [58]:
a1 * ones

array([1., 2., 3.])

In [61]:
a1

array([1, 2, 3])

In [59]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [60]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [62]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [64]:
# How can you reshape a2 to be compatible with a3? 
# Seach: "How to reshape numpy array"
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [65]:
a1 / ones

array([1., 2., 3.])

In [67]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [66]:
# Floor division remove the decimals (round down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [69]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [68]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [70]:
np.square(a2)

10.889999999999999

In [73]:
np.add(a1, ones) # same as {a1 + ones}

array([2., 3., 4.])

In [74]:
a1 % 2

array([1, 0, 1])

In [75]:
a1 / 2

array([0.5, 1. , 1.5])

In [76]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [77]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [78]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation